### PR TITLE
Fix issues with imports

### PR DESCRIPTION
**Pull request by Octogonapus**
This PR fixes a few issues I had with proto imports by fully qualifying them.

### CODE REVIEW

**Comment by nickmertin** [comment]
This is not the correct solution, as it includes hard-coding the relative paths of the files from the perspective of the `bowler-kernel` repository. The correct approach would be to add the appropriate `-I` (include directory) argument to the `protoc` invocation (however one does that through the Gradle plugin), to set the `src/proto/` directory of this repository as an include directory. (An alternative would be to make the root of this repository, or `src/` for that matter, the chosen include directory, but the point being that compiling protos in this repository should not require assumptions about the directory structure outside of the repository.)

**Comment by Octogonapus** [comment]
This is more akin to package names than file paths then? `import "google/protobuf/timestamp.proto";`

**Comment by Octogonapus** [comment]
I have fixed this a different way.

**Comment by nickmertin** [comment]
For reference, `google/protobuf/timestamp.proto` is moreso from a "standard library" of sorts for protobuf, so the authors decided to use that convention (I suspect it also has to do with how they structured it internally before making protobuf public & open source). If we want some sort of project name in our include paths as well, the correct approach would be to move all the `.proto` files to a `bowler/` subdirectory.

**Pull request closed without merging**
